import unittest


class TestDefault(unittest.TestCase):

    def test_sth(self):
        """
        Test that we get no exception when calling the
        the constructor
        """
        pass


if __name__ == '__main__':
    unittest.main()